
image:
    file: .gitpod.Dockerfile

ports:
    - port: 5900
      onOpen: ignore
    - port: 6080
      onOpen: open-preview

vscode:
  extensions:
    - SonarSource.sonarlint-vscode
    - k--kato.intellij-idea-keybindings
    - MoBalic.jetbrains-new-dark
